### ISSUE TITLE
TypeError: paths.forEach is not a function

### ISSUE THREAD

**Issue by dpw1** [kapilpau/react-dynamic-sitemap#5] opened 2020-11-06 22:09 UTC
Hi,

Firstly thank you for the tool, it's highly appreciated!

As aforementioned, when trying to use it I'm getting the following error:

`TypeError: paths.forEach is not a function`

Do you have any idea what it could be? This is how my Routes.js looks like:
```
import React, { useEffect, useState } from "react"; 
import { HashRouter, Route, Link, BrowserRouter } from "react-router-dom";


import HighlightBarAppPage from "./pages/HighlightBarAppPage";
import PortfolioPage from "./pages/PortfolioPage";
import HomePage from "./pages/HomePage";
import BlogDetailsPage from "./pages/BlogDetailsPage";
import BlogsPage from "./pages/BlogsPage";
import Sitemap from "./Sitemap";

function Routes(props) {
  return (
    <BrowserRouter basename="/">
      <div>
        <Route exact path="/" component={() => <HomePage></HomePage>} />
        <Route
          path="/portfolio"
          component={() => <PortfolioPage></PortfolioPage>}
        />
        <Route
          path="/apps/highlight-bar/privacy"
          component={() => <HighlightBarAppPage></HighlightBarAppPage>}
        />

        <Route exact path="/blog" component={() => <BlogsPage />} />

        <Route
          path="/blog/:slug"
          render={(data) => {
            return <BlogDetailsPage data={data} />;
          }}
        />

        <Route path="/sitemap" component={Sitemap} />
      </div>
    </BrowserRouter>
  );
}

export default Routes;
```

Thank you!

**Comment by kapilpau** [comment] 2020-11-06 22:24
Hi @dpw1, the issue is coming from your `div` component. The component works with a structure of:
```js
<TopLevelRouter>
    <Route  />
    <Route />
    ...
</TopLevelRouter>
```

I'm not a react expert, but I don't know a reason as to why you'd need to have the `div` surrounding your Routes.

Hope this solves your issue

**Comment by dpw1** [comment] 2020-11-06 22:57
Hello @kapilpau 

Thank you for very much for the prompt and efficient reply, that did fix the issue! 

On an additional note, it doesn't seem to be generating the sitemap for me. Do you have any idea what that could be?

When I access website.com/sitemap this is the result:

```
<?xml version="1.0" encoding="utf-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"/>

```

**Comment by kapilpau** [comment] 2020-11-06 23:01
Hi @dpw1, looks like you're missing some props. If you scroll to the bottom of the readme, it shows you the required props. The most important one `sitemapIndex: true|false`. This is how you tell the component which routes to display. It defaults to false, so if you don't set it, it won't appear

**Comment by dpw1** [comment] 2020-11-06 23:32
Oh, I see now, so I need to add the `sitemapIndex` to the routes themselves. Thanks!

How would it work with dynamic routes though? For instance, the blogs route is registered as `/blog/:slug`. I see it ends up rendering `website.com/blog/:slug`

Do you reckon it would have a negative impact in the SEO or is it indifferent?

**Comment by kapilpau** [comment] 2020-11-06 23:36
Yeah, dynamic routes do not get "expanded" as yet. If you have a suggestion about how it can be done, please it. Maybe we could have a prop that has values for the slug, and then prints out each one? Not sure what the security/size implications would be.

In terms of SEO, that is completely outside of my skill/knowledge set. I am just a techie, I have a couple of people in my team who do that stuff for us.

**Comment by dpw1** [comment] 2020-11-06 23:44
No worries, I confess SEO is not my expertise either, I mostly repeat what I see that is working around the internet, haha. That said, let's take [Shopify's sitemap](https://www.shopify.com/sitemap.xml) example. 

Although they do have dozens of blog posts, they don't add every single blog post to the sitemap, they add only a few categories as far as I can see.

Therefore, in the case of dynamic pages, perhaps simply removing the appended `:id` could be enough. 🤔

**Comment by kapilpau** [comment] 2020-11-07 13:37
I can add an `override` param to let you override the path that appears, and a `slugs` param to let you expand it out

**Comment by kapilpau** [comment] 2020-11-07 13:40
I will add a `slugs` param which will let you control how they are expanded out, so by setting that to `""`, it will remove the field. I can't give you a timeframe on when this will happen, but in the spirit of open-source, feel free to contribute any changes you think would be good

**Comment by kapilpau** [comment] 2020-12-15 23:30
Hi @dpw1, 

I have added the functionality to support slugs. To enable then, you will need to a `slugs` parameter to the Route objects that you wish to apply them to. The value accepted is an array of JSON objects, where each one represents a URL to fill. see the bottom of the [README](https://github.com/kapilpau/react-dynamic-sitemap) for an example.

I will close this issue, if it doesn't work, please open a new one. Thanks for the feedback on this package, any more suggests are welcome

**Closed as completed by kapilpau** 2020-12-15 23:30 UTC
Labels: enhancement
